import { afterAll, afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { restorePlatform, setPlatform } from './helpers/platform'

const mocks = vi.hoisted(() => ({
  availableFormats: vi.fn((): string[] => []),
  readBuffer: vi.fn((_format: string) => Buffer.alloc(0)),
  has: vi.fn((_format: string) => false),
  read: vi.fn((_format: string) => ''),
  existsSync: vi.fn((_p: string) => true),
  nativeTypes: null as string[] | null,
  bridgeBroken: false
}))

vi.mock('electron', () => ({
  clipboard: {
    availableFormats: () => mocks.availableFormats(),
    readBuffer: (format: string) => mocks.readBuffer(format),
    has: (format: string) => mocks.has(format),
    read: (format: string) => mocks.read(format)
  },
  app: { isPackaged: false, getAppPath: () => '/mock/app', getPath: () => '/mock/userData' }
}))

vi.mock('node:fs', async (importOriginal) => {
  const actual = await importOriginal<typeof import('node:fs')>()
  return { ...actual, existsSync: (p: string) => mocks.existsSync(p) }
})

vi.mock('koffi', async () => ({ default: (await import('./helpers/koffiMock')).pasteboardTypesKoffi(mocks) }))

async function loadFormats(platform: string): Promise<typeof import('../electron/clipboard/formats')> {
  setPlatform(platform)
  vi.resetModules()
  return import('../electron/clipboard/formats')
}

const CONCEALED_TYPES = [
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.TransientType',
  'org.nspasteboard.AutoGeneratedType',
  'com.agilebits.onepassword',
  'de.petermaurer.TransientPasteboardType',
  'com.typeit4me.clipping',
  'Pasteboard generator type'
]

beforeEach(() => {
  mocks.availableFormats.mockReset().mockReturnValue([])
  mocks.readBuffer.mockReset().mockReturnValue(Buffer.alloc(0))
  mocks.has.mockReset().mockReturnValue(false)
  mocks.read.mockReset().mockReturnValue('')
  mocks.existsSync.mockReset().mockReturnValue(true)
  mocks.nativeTypes = null
  mocks.bridgeBroken = false
})

afterEach(() => {
  restorePlatform()
})

afterAll(() => {
  restorePlatform()
})

describe('hasExcludedPasteboardType', () => {
  it('flags every nspasteboard.org and password-manager type', async () => {
    const { hasExcludedPasteboardType } = await loadFormats('darwin')
    for (const type of CONCEALED_TYPES) {
      expect(hasExcludedPasteboardType(['public.utf8-plain-text', type])).toBe(true)
    }
  })

  it('matches case-insensitively', async () => {
    const { hasExcludedPasteboardType } = await loadFormats('darwin')
    expect(hasExcludedPasteboardType(['org.nspasteboard.concealedtype'])).toBe(true)
  })

  it('passes ordinary text, image and file copies', async () => {
    const { hasExcludedPasteboardType } = await loadFormats('darwin')
    expect(hasExcludedPasteboardType([])).toBe(false)
    expect(hasExcludedPasteboardType(['public.utf8-plain-text', 'public.html', 'public.png', 'public.file-url', 'NSFilenamesPboardType'])).toBe(false)
  })
})

describe('isClipboardExcluded on darwin', () => {
  it('excludes when the native pasteboard lists a concealed type that Electron does not report', async () => {
    mocks.nativeTypes = ['public.utf8-plain-text', 'org.nspasteboard.ConcealedType']
    mocks.availableFormats.mockReturnValue(['text/plain'])
    const { isClipboardExcluded, macPasteboardTypes } = await loadFormats('darwin')
    expect(macPasteboardTypes()).toEqual(['public.utf8-plain-text', 'org.nspasteboard.ConcealedType'])
    expect(isClipboardExcluded()).toBe(true)
    expect(mocks.has).not.toHaveBeenCalled()
  })

  it('excludes transient and auto-generated content', async () => {
    const { isClipboardExcluded } = await loadFormats('darwin')
    for (const type of ['org.nspasteboard.TransientType', 'org.nspasteboard.AutoGeneratedType', 'Pasteboard generator type']) {
      mocks.nativeTypes = ['public.utf8-plain-text', type]
      expect(isClipboardExcluded()).toBe(true)
    }
  })

  it('falls back to clipboard.has when the native bridge is unavailable', async () => {
    mocks.bridgeBroken = true
    const errorSpy = vi.spyOn(console, 'error').mockImplementation(() => {})
    const { isClipboardExcluded, macPasteboardTypes } = await loadFormats('darwin')
    errorSpy.mockRestore()
    expect(macPasteboardTypes()).toBeNull()
    expect(isClipboardExcluded()).toBe(false)
    mocks.has.mockImplementation((format: string) => format === 'de.petermaurer.TransientPasteboardType')
    expect(isClipboardExcluded()).toBe(true)
  })

  it('survives clipboard.has throwing', async () => {
    mocks.nativeTypes = ['public.utf8-plain-text']
    mocks.has.mockImplementation(() => {
      throw new Error('boom')
    })
    const { isClipboardExcluded } = await loadFormats('darwin')
    expect(isClipboardExcluded()).toBe(false)
  })

  it('keeps ordinary copies', async () => {
    mocks.nativeTypes = ['public.utf8-plain-text', 'public.html']
    mocks.availableFormats.mockReturnValue(['text/plain', 'text/html'])
    const { isClipboardExcluded } = await loadFormats('darwin')
    expect(isClipboardExcluded()).toBe(false)
  })
})

describe('isClipboardExcluded on win32', () => {
  it('never consults the mac pasteboard checks', async () => {
    mocks.nativeTypes = ['org.nspasteboard.ConcealedType']
    mocks.has.mockReturnValue(true)
    const { isClipboardExcluded, macPasteboardTypes } = await loadFormats('win32')
    expect(macPasteboardTypes()).toBeNull()
    expect(isClipboardExcluded()).toBe(false)
    expect(mocks.has).not.toHaveBeenCalled()
  })

  it('still honours the Windows privacy formats', async () => {
    const { isClipboardExcluded } = await loadFormats('win32')
    mocks.availableFormats.mockReturnValue(['excludeclipboardcontentfrommonitorprocessing'])
    expect(isClipboardExcluded()).toBe(true)
    mocks.availableFormats.mockReturnValue(['text/plain'])
    mocks.readBuffer.mockImplementation((format: string) =>
      format === 'CanIncludeInClipboardHistory' ? Buffer.from([0, 0, 0, 0]) : Buffer.alloc(0)
    )
    expect(isClipboardExcluded()).toBe(true)
  })
})

describe('formatTabularDataForClipboard line endings', () => {
  const table = '<table border="0" cellpadding="0" cellspacing="0"><tbody><tr><td>a</td><td>b</td></tr><tr><td>c</td><td>d</td></tr></tbody></table>'

  it('leaves multiline text untouched on darwin', async () => {
    const { formatTabularDataForClipboard } = await loadFormats('darwin')
    expect(formatTabularDataForClipboard('line 1\nline 2\nline 3')).toEqual({ text: 'line 1\nline 2\nline 3', html: undefined })
    expect(formatTabularDataForClipboard('line 1\r\nline 2').text).toBe('line 1\r\nline 2')
  })

  it('leaves multiline text untouched on linux', async () => {
    const { formatTabularDataForClipboard } = await loadFormats('linux')
    expect(formatTabularDataForClipboard('line 1\nline 2').text).toBe('line 1\nline 2')
  })

  it('still converts to CRLF on win32', async () => {
    const { formatTabularDataForClipboard } = await loadFormats('win32')
    expect(formatTabularDataForClipboard('line 1\nline 2\r\nline 3')).toEqual({ text: 'line 1\r\nline 2\r\nline 3', html: undefined })
    expect(formatTabularDataForClipboard('a\tb\nc\td')).toEqual({ text: 'a\tb\r\nc\td', html: table })
  })

  it('synthesizes the same HTML table on darwin for LF and CRLF input', async () => {
    const { formatTabularDataForClipboard } = await loadFormats('darwin')
    expect(formatTabularDataForClipboard('a\tb\nc\td')).toEqual({ text: 'a\tb\nc\td', html: table })
    expect(formatTabularDataForClipboard('a\tb\r\nc\td')).toEqual({ text: 'a\tb\r\nc\td', html: table })
  })

  it('keeps an existing table and skips synthesis for heavy TSV on darwin', async () => {
    const { formatTabularDataForClipboard } = await loadFormats('darwin')
    const html = '<table><tr><td>a</td><td>b</td></tr></table>'
    expect(formatTabularDataForClipboard('a\tb\nc\td', html)).toEqual({ text: 'a\tb\nc\td', html })
    const heavy = Array.from({ length: 1500 }, (_, i) => `r${i}\tc${i}`).join('\n')
    const result = formatTabularDataForClipboard(heavy)
    expect(result.text).toBe(heavy)
    expect(result.html).toBeUndefined()
  })
})

describe('localPathFromClipboardFileUrl', () => {
  it('keeps the leading slash on darwin', async () => {
    const { localPathFromClipboardFileUrl } = await loadFormats('darwin')
    expect(localPathFromClipboardFileUrl('file:///Users/a/My%20File.png')).toBe('/Users/a/My File.png')
    expect(mocks.existsSync).toHaveBeenCalledWith('/Users/a/My File.png')
  })

  it('handles file://localhost/ urls on darwin', async () => {
    const { localPathFromClipboardFileUrl } = await loadFormats('darwin')
    expect(localPathFromClipboardFileUrl('file://localhost/Users/a/x.png')).toBe('/Users/a/x.png')
  })

  it('finds the url inside html on darwin', async () => {
    const { localPathFromClipboardFileUrl, extractClipboardImageFileName } = await loadFormats('darwin')
    const html = '<img src="file:///Users/a/Pictures/%D0%A4%D0%BE%D1%82%D0%BE.png" alt="x">'
    expect(localPathFromClipboardFileUrl(html)).toBe('/Users/a/Pictures/Фото.png')
    expect(extractClipboardImageFileName('', html)).toBe('Фото.png')
  })

  it('keeps the leading slash on linux', async () => {
    const { localPathFromClipboardFileUrl } = await loadFormats('linux')
    expect(localPathFromClipboardFileUrl('file:///home/a/x.png')).toBe('/home/a/x.png')
  })

  it('returns null on darwin for a missing file, a non-file url and bad percent-encoding', async () => {
    const { localPathFromClipboardFileUrl } = await loadFormats('darwin')
    expect(localPathFromClipboardFileUrl('https://example.com/a.png')).toBeNull()
    expect(localPathFromClipboardFileUrl('file:///Users/a/100%.png')).toBeNull()
    mocks.existsSync.mockReturnValue(false)
    expect(localPathFromClipboardFileUrl('file:///Users/a/gone.png')).toBeNull()
  })

  it('keeps the Windows drive-letter forms on win32', async () => {
    const { localPathFromClipboardFileUrl } = await loadFormats('win32')
    expect(localPathFromClipboardFileUrl('file:///C:/Users/a/My%20File.png')).toBe('C:\\Users\\a\\My File.png')
    expect(localPathFromClipboardFileUrl('file://C:/Users/a/x.png')).toBe('C:\\Users\\a\\x.png')
    expect(localPathFromClipboardFileUrl('file:///c/Users/a/x.png')).toBe('c:\\Users\\a\\x.png')
    expect(localPathFromClipboardFileUrl('<img src="file:///D:/pics/x.png">')).toBe('D:\\pics\\x.png')
  })

  it('keeps the Windows UNC form on win32', async () => {
    const { localPathFromClipboardFileUrl } = await loadFormats('win32')
    expect(localPathFromClipboardFileUrl('file://\\\\server\\share\\x.png')).toBe('\\\\server\\share\\x.png')
  })
})

describe('localPathFromFileUrl', () => {
  it('keeps an apostrophe and a double quote in a bare url on darwin', async () => {
    const { localPathFromFileUrl } = await loadFormats('darwin')
    expect(localPathFromFileUrl("file:///Users/me/it's.png")).toBe("/Users/me/it's.png")
    expect(localPathFromFileUrl('file:///Users/me/say%20"hi".png')).toBe('/Users/me/say "hi".png')
    expect(mocks.existsSync).toHaveBeenCalledWith("/Users/me/it's.png")
  })

  it('handles localhost, percent-encoding and surrounding whitespace on darwin', async () => {
    const { localPathFromFileUrl } = await loadFormats('darwin')
    expect(localPathFromFileUrl('file://localhost/Users/a/x.png')).toBe('/Users/a/x.png')
    expect(localPathFromFileUrl(' file:///Users/a/My%20File.png\n')).toBe('/Users/a/My File.png')
  })

  it('returns null for text that merely contains a url, a missing file and bad percent-encoding', async () => {
    const { localPathFromFileUrl } = await loadFormats('darwin')
    expect(localPathFromFileUrl('<img src="file:///Users/a/x.png">')).toBeNull()
    expect(localPathFromFileUrl('https://example.com/a.png')).toBeNull()
    expect(localPathFromFileUrl('file:///Users/a/100%.png')).toBeNull()
    mocks.existsSync.mockReturnValue(false)
    expect(localPathFromFileUrl("file:///Users/me/it's.png")).toBeNull()
  })

  it('still ends an embedded url at the attribute quote', async () => {
    const { localPathFromClipboardFileUrl } = await loadFormats('darwin')
    expect(localPathFromClipboardFileUrl("<img src='file:///Users/a/x.png' alt='y'>")).toBe('/Users/a/x.png')
    expect(localPathFromClipboardFileUrl('<img src="file:///Users/a/x.png" alt="y">')).toBe('/Users/a/x.png')
  })

  it('uses the unchanged Windows parser on win32', async () => {
    const { localPathFromFileUrl } = await loadFormats('win32')
    expect(localPathFromFileUrl('file:///C:/Users/a/My%20File.png')).toBe('C:\\Users\\a\\My File.png')
    expect(localPathFromFileUrl('<img src="file:///D:/pics/x.png">')).toBe('D:\\pics\\x.png')
  })
})

describe('detectClipboardImageSource', () => {
  it('treats an image-only pasteboard as a screenshot on darwin', async () => {
    mocks.availableFormats.mockReturnValue(['image/png'])
    mocks.nativeTypes = ['public.png', 'public.tiff']
    const { detectClipboardImageSource } = await loadFormats('darwin')
    expect(detectClipboardImageSource('', '')).toBe('screenshot')
  })

  it('treats an image with text or html next to it as an image on darwin', async () => {
    mocks.availableFormats.mockReturnValue(['image/png'])
    const { detectClipboardImageSource } = await loadFormats('darwin')
    expect(detectClipboardImageSource('Window title', '')).toBe('image')
    expect(detectClipboardImageSource('https://example.com/a.png', '')).toBe('image')
    expect(detectClipboardImageSource('', '<img src="https://example.com/a.png">')).toBe('image')
  })

  it('treats non-image Electron formats as an image on darwin', async () => {
    const { detectClipboardImageSource } = await loadFormats('darwin')
    for (const formats of [['image/png', 'text/html'], ['text/plain', 'image/png'], ['image/png', 'text/uri-list']]) {
      mocks.availableFormats.mockReturnValue(formats)
      expect(detectClipboardImageSource('', '')).toBe('image')
    }
  })

  it('treats a file-url next to the image as an image on darwin', async () => {
    mocks.availableFormats.mockReturnValue(['image/png'])
    const { detectClipboardImageSource } = await loadFormats('darwin')
    mocks.read.mockImplementation((format: string) => (format === 'public.file-url' ? 'file:///Users/a/x.png' : ''))
    expect(detectClipboardImageSource('', '')).toBe('image')
    mocks.read.mockReturnValue('')
    mocks.nativeTypes = ['public.png', 'public.url']
    expect(detectClipboardImageSource('', '')).toBe('image')
  })

  it('keeps the Windows heuristic on win32', async () => {
    const { detectClipboardImageSource } = await loadFormats('win32')
    mocks.availableFormats.mockReturnValue(['image/png'])
    expect(detectClipboardImageSource('', '')).toBe('screenshot')
    expect(detectClipboardImageSource('Untitled - Notepad', '')).toBe('screenshot')
    expect(detectClipboardImageSource('https://example.com/a.png', '')).toBe('image')
    mocks.availableFormats.mockReturnValue(['image/png', 'text/html'])
    expect(detectClipboardImageSource('', '')).toBe('screenshot')
    mocks.availableFormats.mockReturnValue(['FileGroupDescriptorW', 'image/png'])
    expect(detectClipboardImageSource('', '')).toBe('image')
  })
})
