import { clipboard } from 'electron'
import { macPasteboardTypes } from './nativeClipboard'

/** Sensitive clipboard formats used by password managers and transient scripts. */
const IGNORED_FORMATS = [
  'ClipboardViewerIgnore',
  'Clipboard Viewer Ignore',
  'ExcludeClipboardContentFromMonitorProcessing',
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.AutoGeneratedType',
  'com.agilebits.onepassword',
  'com.apple.is-sensitive',
  'com.apple.pasteboard.concealed',
  'KeePassClipFormat',
  'com.bitwarden.concealed'
]

/**
 * Windows registered clipboard format names are compared case-insensitively by
 * the OS, but `availableFormats()` returns whatever casing the registering app
 * used. So a privacy flag like `ExcludeClipboardContentFromMonitorProcessing`
 * may arrive in any casing — we must match it case-insensitively, otherwise
 * content a password manager / dictation tool explicitly marked "do not record"
 * still leaks into our history (and out of Windows' own Win+V history).
 */
function isIgnoredFormat(format: string): boolean {
  const lower = format.toLowerCase()
  return IGNORED_FORMATS.some((f) => f.toLowerCase() === lower)
}

const MAC_EXCLUDED_PASTEBOARD_TYPES = [
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.TransientType',
  'org.nspasteboard.AutoGeneratedType',
  'com.agilebits.onepassword',
  'de.petermaurer.TransientPasteboardType',
  'com.typeit4me.clipping',
  'Pasteboard generator type'
]

export function hasExcludedPasteboardType(types: readonly string[]): boolean {
  return types.some((type) => {
    const lower = type.toLowerCase()
    return MAC_EXCLUDED_PASTEBOARD_TYPES.some((t) => t.toLowerCase() === lower) || isIgnoredFormat(type)
  })
}

function isMacClipboardExcluded(): boolean {
  const types = macPasteboardTypes()
  if (types && hasExcludedPasteboardType(types)) return true
  return MAC_EXCLUDED_PASTEBOARD_TYPES.some((t) => {
    try {
      return clipboard.has(t)
    } catch {
      return false
    }
  })
}

/**
 * Checks whether the current clipboard content is marked as sensitive, confidential,
 * or transient (e.g. by password managers, dictation tools, or macro scripts)
 * and should be ignored by clipboard monitors.
 */
export function isClipboardExcluded(): boolean {
  const formats = clipboard.availableFormats()

  if (formats.some((f) => isIgnoredFormat(f))) {
    return true
  }

  if (process.platform === 'darwin' && isMacClipboardExcluded()) {
    return true
  }

  // Explicitly check known privacy formats because Chromium often hides them from availableFormats()
  const checkExplicitExclusion = (format: string, isExcluded: (buf: Buffer) => boolean) => {
    try {
      const buf = clipboard.readBuffer(format)
      if (!buf || buf.length === 0) return false
      return isExcluded(buf)
    } catch {
      return false
    }
  }

  // CanIncludeInClipboardHistory: 0 means DO NOT include
  if (checkExplicitExclusion('CanIncludeInClipboardHistory', (buf) => buf.length >= 4 && buf.readUInt32LE(0) === 0)) {
    return true
  }

  // CanUploadToCloudClipboard: 0 means DO NOT include
  if (checkExplicitExclusion('CanUploadToCloudClipboard', (buf) => buf.length >= 4 && buf.readUInt32LE(0) === 0)) {
    return true
  }

  // ExcludeClipboardContentFromMonitorProcessing: non-zero means EXCLUDE
  if (checkExplicitExclusion('ExcludeClipboardContentFromMonitorProcessing', (buf) => buf.length >= 4 && buf.readUInt32LE(0) !== 0)) {
    return true
  }

  // Clipboard Viewer Ignore: presence of format with data means EXCLUDE
  if (checkExplicitExclusion('Clipboard Viewer Ignore', () => true)) {
    return true
  }

  return false
}
